'use client';
import { useEffect,useMemo,useState } from 'react';
import { Home,Package,ShoppingCart,BarChart3,Settings,Search,Plus,Minus,Banknote,QrCode,Trash2,RefreshCw,Pencil,Boxes,X } from 'lucide-react';
type Product={id:number;sku?:string;barcode?:string;qr_code?:string;name:string;price:number|string;cost?:number|string;stock_qty:number|string;low_stock_qty?:number|string;unit:string;category?:string}; type Cart=Product&{qty:number}; type Dashboard={todayRevenue:number;todayBills:number;products:number;lowStock:number};
const blank={sku:'',barcode:'',qr_code:'',name:'',category:'',cost:'0',price:'0',stock_qty:'0',low_stock_qty:'5',unit:'ชิ้น'}; const emoji=(c?:string)=>c==='เครื่องดื่ม'?'🥤':c==='อาหาร'?'🍱':c==='เสื้อผ้า'?'👕':'📦';
export default function Page(){
 const [tab,setTab]=useState('ขาย'),[products,setProducts]=useState<Product[]>([]),[cart,setCart]=useState<Cart[]>([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[paying,setPaying]=useState(false),[message,setMessage]=useState(''),[dash,setDash]=useState<Dashboard>({todayRevenue:0,todayBills:0,products:0,lowStock:0}); const [form,setForm]=useState<any>(blank),[editing,setEditing]=useState<number|null>(null),[showForm,setShowForm]=useState(false),[stockProduct,setStockProduct]=useState<Product|null>(null),[stockQty,setStockQty]=useState('');
 const load=async()=>{setLoading(true);try{const[p,d]=await Promise.all([fetch('/api/products',{cache:'no-store'}),fetch('/api/dashboard',{cache:'no-store'})]);if(!p.ok||!d.ok)throw Error();setProducts((await p.json()).products||[]);setDash(await d.json())}catch{setMessage('เชื่อมต่อฐานข้อมูลไม่สำเร็จ')}finally{setLoading(false)}}; useEffect(()=>{load()},[]);
 const total=cart.reduce((s,i)=>s+Number(i.price)*i.qty,0),count=cart.reduce((s,i)=>s+i.qty,0); const filtered=useMemo(()=>products.filter(p=>(p.name+' '+(p.sku||'')+' '+(p.barcode||'')+' '+(p.qr_code||'')).toLowerCase().includes(query.toLowerCase())),[products,query]);
 const add=(p:Product)=>{if(Number(p.stock_qty)<=0)return;setCart(c=>{const x=c.find(i=>i.id===p.id);if(x&&x.qty>=Number(p.stock_qty))return c;return x?c.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...c,{...p,qty:1}]})}; const qty=(id:number,d:number)=>setCart(c=>c.map(i=>i.id===id?{...i,qty:Math.min(i.qty+d,Number(i.stock_qty))}:i).filter(i=>i.qty>0));
 const checkout=async(method:'cash'|'promptpay')=>{if(!cart.length||paying)return;setPaying(true);try{const r=await fetch('/api/sales',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({paymentMethod:method,items:cart.map(i=>({productId:i.id,quantity:i.qty}))})});const x=await r.json();if(!r.ok)throw Error(x.error);setMessage(`✓ บิล ${x.receiptNo} สำเร็จ ฿${Number(x.total).toLocaleString()}`);setCart([]);await load()}catch(e:any){setMessage(e.message||'บันทึกไม่สำเร็จ')}finally{setPaying(false)}};
 const openNew=()=>{setEditing(null);setForm(blank);setShowForm(true)}; const openEdit=(p:Product)=>{setEditing(p.id);setForm({...p,stock_qty:String(p.stock_qty)});setShowForm(true)}; const saveProduct=async()=>{if(!form.name)return setMessage('กรุณาระบุชื่อสินค้า');const r=await fetch(editing?`/api/products/${editing}`:'/api/products',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}),x=await r.json();if(!r.ok)return setMessage(x.error||'บันทึกไม่สำเร็จ');setShowForm(false);setMessage('✓ บันทึกสินค้าแล้ว');await load()}; const del=async(p:Product)=>{if(!confirm(`ลบ ${p.name} ?`))return;const r=await fetch(`/api/products/${p.id}`,{method:'DELETE'});if(r.ok){setMessage('✓ ลบสินค้าแล้ว');await load()}};
 const adjustStock=async()=>{if(!stockProduct||!Number(stockQty))return;const r=await fetch('/api/stock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId:stockProduct.id,quantity:Number(stockQty),type:Number(stockQty)>0?'receive':'adjust',note:'ปรับจากหน้าจัดการสินค้า'})}),x=await r.json();if(!r.ok)return setMessage(x.error);setStockProduct(null);setStockQty('');setMessage('✓ ปรับสต๊อกแล้ว');await load()};
 return <main className="shell"><header><div><small>MARKET POS • ONLINE</small><h1>{tab==='ขาย'?'ขายสินค้า':tab}</h1></div><button className="avatar" onClick={load}><RefreshCw size={18}/></button></header>{message&&<p className={message.startsWith('✓')?'success':'notice'}>{message}</p>}
 {tab==='หน้าหลัก'&&<section><div className="hero"><span>ยอดขายวันนี้</span><strong>฿{Number(dash.todayRevenue||0).toLocaleString()}</strong><small>{dash.todayBills||0} บิล • Neon PostgreSQL</small></div><div className="stats"><article><b>{dash.products}</b><span>สินค้าทั้งหมด</span></article><article><b>{dash.lowStock}</b><span>สินค้าใกล้หมด</span></article></div></section>}
 {tab==='ขาย'&&<section><div className="search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหา / SKU / Barcode / QR Code"/></div>{loading?<p>กำลังโหลด...</p>:<div className="grid">{filtered.map(p=><button className="product" key={p.id} onClick={()=>add(p)} disabled={Number(p.stock_qty)<=0}><span className="emoji">{emoji(p.category)}</span><b>{p.name}</b><small>คงเหลือ {Number(p.stock_qty)} {p.unit}</small><strong>฿{Number(p.price).toLocaleString()}</strong></button>)}</div>}{cart.length>0&&<div className="cart"><div className="cartTitle"><b><ShoppingCart size={18}/> ตะกร้า ({count})</b><button onClick={()=>setCart([])}><Trash2 size={17}/></button></div>{cart.map(i=><div className="cartRow" key={i.id}><span>{i.name}<small>฿{Number(i.price).toLocaleString()}</small></span><div><button onClick={()=>qty(i.id,-1)}><Minus/></button><b>{i.qty}</b><button onClick={()=>qty(i.id,1)}><Plus/></button></div></div>)}<div className="total"><span>ยอดรวม</span><strong>฿{total.toLocaleString()}</strong></div><div className="pay"><button disabled={paying} onClick={()=>checkout('cash')}><Banknote/> เงินสด</button><button disabled={paying} onClick={()=>checkout('promptpay')}><QrCode/> PromptPay</button></div></div>}</section>}
 {tab==='สินค้า'&&<section><div className="manageHead"><div><b>จัดการสินค้า</b><small>{products.length} รายการ • ใกล้หมด {dash.lowStock}</small></div><button className="primary" onClick={openNew}><Plus/> เพิ่มสินค้า</button></div><div className="search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหา SKU / Barcode / QR"/></div>{filtered.map(p=><div className={Number(p.stock_qty)<=Number(p.low_stock_qty||0)?'manageRow low':'manageRow'} key={p.id}><div className="prodInfo"><span>{emoji(p.category)}</span><div><b>{p.name}</b><small>{p.sku||'-'} • ฿{Number(p.price).toLocaleString()} • คงเหลือ {Number(p.stock_qty)} {p.unit}</small>{p.qr_code&&<small>QR: {p.qr_code}</small>}</div></div><div className="actions"><button onClick={()=>{setStockProduct(p);setStockQty('')}}><Boxes/></button><button onClick={()=>openEdit(p)}><Pencil/></button><button onClick={()=>del(p)}><Trash2/></button></div></div>)}</section>}
 {tab==='รายงาน'&&<section><div className="hero"><span>ยอดขายวันนี้</span><strong>฿{Number(dash.todayRevenue||0).toLocaleString()}</strong><small>{dash.todayBills} บิล</small></div><div className="stats"><article><b>{dash.products}</b><span>รายการสินค้า</span></article><article><b>{dash.lowStock}</b><span>ใกล้หมด</span></article></div></section>}{tab==='ตั้งค่า'&&<section><h2>ตั้งค่าร้านค้า</h2>{['ข้อมูลร้านค้า','PromptPay / QR รับเงิน','เครื่องพิมพ์ใบเสร็จ','พนักงานและสิทธิ์','สำรองข้อมูล'].map(x=><div className="row" key={x}><span>{x}</span><b>›</b></div>)}</section>}
 {showForm&&<div className="overlay"><div className="modal"><div className="modalHead"><b>{editing?'แก้ไขสินค้า':'เพิ่มสินค้า'}</b><button onClick={()=>setShowForm(false)}><X/></button></div><div className="formGrid">{[['sku','SKU'],['barcode','Barcode'],['qr_code','ข้อมูล QR Code'],['name','ชื่อสินค้า'],['category','หมวดหมู่'],['cost','ราคาทุน'],['price','ราคาขาย'],['low_stock_qty','แจ้งเตือนเมื่อเหลือ'],['unit','หน่วย']].map(([k,l])=><label key={k}><span>{l}</span><input type={['cost','price','low_stock_qty'].includes(k)?'number':'text'} value={form[k]??''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}{!editing&&<label><span>สต๊อกเริ่มต้น</span><input type="number" value={form.stock_qty} onChange={e=>setForm({...form,stock_qty:e.target.value})}/></label>}</div><button className="save" onClick={saveProduct}>บันทึกสินค้า</button></div></div>}
 {stockProduct&&<div className="overlay"><div className="modal"><div className="modalHead"><b>ปรับสต๊อก • {stockProduct.name}</b><button onClick={()=>setStockProduct(null)}><X/></button></div><p>คงเหลือปัจจุบัน <b>{Number(stockProduct.stock_qty)} {stockProduct.unit}</b></p><label><span>จำนวน (+ รับเข้า / - ปรับออก)</span><input className="bigInput" type="number" value={stockQty} onChange={e=>setStockQty(e.target.value)} placeholder="เช่น 10 หรือ -2"/></label><button className="save" onClick={adjustStock}>บันทึกสต๊อก</button></div></div>}
 <nav>{[['หน้าหลัก',Home],['สินค้า',Package],['ขาย',ShoppingCart],['รายงาน',BarChart3],['ตั้งค่า',Settings]].map(([n,I]:any)=><button className={tab===n?'active':''} onClick={()=>setTab(n)} key={n}><I/><span>{n}</span></button>)}</nav></main>}
